// <auto-generated />
using System;
using HottaPiz.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HottaPiz.DataLayer.Migrations
{
    [DbContext(typeof(HottaPizContext))]
    [Migration("20220702130252_Mig_UpdateTables")]
    partial class Mig_UpdateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HottaPiz.DataLayer.Entities.Customer.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CustomerEmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerFirstAddress")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("CustomerFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CustomerRegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerSecondAddress")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("HottaPiz.DataLayer.Entities.Order.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentGateWay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentTraceCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalOrderPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HottaPiz.DataLayer.Entities.Order.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaId");

                    b.ToTable("OrdersDetails");
                });

            modelBuilder.Entity("HottaPiz.DataLayer.Entities.Pizza.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCustomPizza")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PizzaBasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PizzaImageName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PizzaName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PizzaTotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6992),
                            Description = "",
                            IsCustomPizza = false,
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6995),
                            PizzaBasePrice = 5m,
                            PizzaImageName = "Veggie Pizza.png",
                            PizzaName = "Veggie Pizza",
                            PizzaTotalPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7000),
                            Description = "",
                            IsCustomPizza = false,
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7001),
                            PizzaBasePrice = 5m,
                            PizzaImageName = "Pepperoni Pizza.png",
                            PizzaName = "Pepperoni Pizza",
                            PizzaTotalPrice = 0m
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7004),
                            Description = "",
                            IsCustomPizza = false,
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7005),
                            PizzaBasePrice = 5m,
                            PizzaImageName = "Cheese Pizza.png",
                            PizzaName = "Cheese Pizza",
                            PizzaTotalPrice = 0m
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7008),
                            Description = "",
                            IsCustomPizza = false,
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7009),
                            PizzaBasePrice = 5m,
                            PizzaImageName = "Meats Pizza.png",
                            PizzaName = "Meats Pizza",
                            PizzaTotalPrice = 0m
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7012),
                            Description = "",
                            IsCustomPizza = false,
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7013),
                            PizzaBasePrice = 5m,
                            PizzaImageName = "Margherita Pizza.png",
                            PizzaName = "Margherita Pizza",
                            PizzaTotalPrice = 0m
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7016),
                            Description = "",
                            IsCustomPizza = false,
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7017),
                            PizzaBasePrice = 5m,
                            PizzaImageName = "BBQ Chicken Pizza.png",
                            PizzaName = "BBQ Chicken Pizza",
                            PizzaTotalPrice = 0m
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7020),
                            Description = "",
                            IsCustomPizza = false,
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7021),
                            PizzaBasePrice = 5m,
                            PizzaImageName = "Hawaiian Pizza.png",
                            PizzaName = "Hawaiian Pizza",
                            PizzaTotalPrice = 0m
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7024),
                            Description = "",
                            IsCustomPizza = false,
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7025),
                            PizzaBasePrice = 5m,
                            PizzaImageName = "Buffalo Pizza.png",
                            PizzaName = "Buffalo Pizza",
                            PizzaTotalPrice = 0m
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7028),
                            Description = "",
                            IsCustomPizza = false,
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7029),
                            PizzaBasePrice = 5m,
                            PizzaImageName = "Supreme Pizza.png",
                            PizzaName = "Supreme Pizza",
                            PizzaTotalPrice = 0m
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7032),
                            Description = "",
                            IsCustomPizza = false,
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(7033),
                            PizzaBasePrice = 5m,
                            PizzaImageName = "The Works Pizza.png",
                            PizzaName = "The Works Pizza",
                            PizzaTotalPrice = 0m
                        });
                });

            modelBuilder.Entity("HottaPiz.DataLayer.Entities.Pizza.PizzaIngredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("IngredientPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IngredientTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PizzasIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientPrice = 0.49m,
                            IngredientTitle = "Mushroom",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6737)
                        },
                        new
                        {
                            Id = 2,
                            IngredientPrice = 3.99m,
                            IngredientTitle = "Beef",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6769)
                        },
                        new
                        {
                            Id = 3,
                            IngredientPrice = 2.99m,
                            IngredientTitle = "Ham",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6772)
                        },
                        new
                        {
                            Id = 4,
                            IngredientPrice = 1.99m,
                            IngredientTitle = "Chicken",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6775)
                        },
                        new
                        {
                            Id = 5,
                            IngredientPrice = 1.99m,
                            IngredientTitle = "Pepperoni",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6777)
                        },
                        new
                        {
                            Id = 6,
                            IngredientPrice = 1.99m,
                            IngredientTitle = "Bologna",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6780)
                        },
                        new
                        {
                            Id = 7,
                            IngredientPrice = 0.49m,
                            IngredientTitle = "CheddarCheese",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6783)
                        },
                        new
                        {
                            Id = 8,
                            IngredientPrice = 0.49m,
                            IngredientTitle = "GoudaCheese",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6785)
                        },
                        new
                        {
                            Id = 9,
                            IngredientPrice = 0.49m,
                            IngredientTitle = "Olive",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6787)
                        },
                        new
                        {
                            Id = 10,
                            IngredientPrice = 6.99m,
                            IngredientTitle = "Pineapple",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6790)
                        },
                        new
                        {
                            Id = 11,
                            IngredientPrice = 0.49m,
                            IngredientTitle = "Tomato",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6792)
                        },
                        new
                        {
                            Id = 12,
                            IngredientPrice = 0.49m,
                            IngredientTitle = "Onion",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6795)
                        },
                        new
                        {
                            Id = 13,
                            IngredientPrice = 0.49m,
                            IngredientTitle = "Potato",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6797)
                        },
                        new
                        {
                            Id = 14,
                            IngredientPrice = 0.49m,
                            IngredientTitle = "SweatPepper",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6799)
                        },
                        new
                        {
                            Id = 15,
                            IngredientPrice = 0.99m,
                            IngredientTitle = "Vegetable",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6801)
                        },
                        new
                        {
                            Id = 16,
                            IngredientPrice = 0m,
                            IngredientTitle = "TomatoSauce",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6804)
                        },
                        new
                        {
                            Id = 17,
                            IngredientPrice = 0m,
                            IngredientTitle = "FrenchSauce",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6806)
                        },
                        new
                        {
                            Id = 18,
                            IngredientPrice = 0m,
                            IngredientTitle = "MayonnaiseSauce",
                            IsDelete = false,
                            LastModifiedDate = new DateTime(2022, 7, 2, 17, 32, 52, 114, DateTimeKind.Local).AddTicks(6809)
                        });
                });

            modelBuilder.Entity("HottaPiz.DataLayer.Entities.Pizza.PizzaToIngredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("PizzaIngredientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.HasIndex("PizzaIngredientId");

                    b.ToTable("PizzaToIngredients");
                });

            modelBuilder.Entity("HottaPiz.DataLayer.Entities.Order.Order", b =>
                {
                    b.HasOne("HottaPiz.DataLayer.Entities.Customer.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HottaPiz.DataLayer.Entities.Order.OrderDetails", b =>
                {
                    b.HasOne("HottaPiz.DataLayer.Entities.Order.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HottaPiz.DataLayer.Entities.Pizza.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HottaPiz.DataLayer.Entities.Pizza.Pizza", b =>
                {
                    b.HasOne("HottaPiz.DataLayer.Entities.Customer.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("HottaPiz.DataLayer.Entities.Pizza.PizzaToIngredients", b =>
                {
                    b.HasOne("HottaPiz.DataLayer.Entities.Pizza.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HottaPiz.DataLayer.Entities.Pizza.PizzaIngredients", null)
                        .WithMany()
                        .HasForeignKey("PizzaIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
